// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/uber/cadence/service/history/taskdlq (interfaces: TaskReinjector)
//
// Generated by this command:
//
//	mockgen -package taskdlq -destination interface_mock.go github.com/uber/cadence/service/history/taskdlq TaskReinjector
//

// Package taskdlq is a generated GoMock package.
package taskdlq

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	persistence "github.com/uber/cadence/common/persistence"
)

// MockTaskReinjector is a mock of TaskReinjector interface.
type MockTaskReinjector struct {
	ctrl     *gomock.Controller
	recorder *MockTaskReinjectorMockRecorder
	isgomock struct{}
}

// MockTaskReinjectorMockRecorder is the mock recorder for MockTaskReinjector.
type MockTaskReinjectorMockRecorder struct {
	mock *MockTaskReinjector
}

// NewMockTaskReinjector creates a new mock instance.
func NewMockTaskReinjector(ctrl *gomock.Controller) *MockTaskReinjector {
	mock := &MockTaskReinjector{ctrl: ctrl}
	mock.recorder = &MockTaskReinjectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskReinjector) EXPECT() *MockTaskReinjectorMockRecorder {
	return m.recorder
}

// ReinjectHistoryTasks mocks base method.
func (m *MockTaskReinjector) ReinjectHistoryTasks(ctx context.Context, tasks []persistence.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReinjectHistoryTasks", ctx, tasks)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReinjectHistoryTasks indicates an expected call of ReinjectHistoryTasks.
func (mr *MockTaskReinjectorMockRecorder) ReinjectHistoryTasks(ctx, tasks any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReinjectHistoryTasks", reflect.TypeOf((*MockTaskReinjector)(nil).ReinjectHistoryTasks), ctx, tasks)
}
