package ratelimited

// Code generated by gowrap. DO NOT EDIT.
// template: ../templates/ratelimited.tmpl
// gowrap: http://github.com/hexdigest/gowrap

import (
	"context"

	"github.com/uber/cadence/common/dynamicconfig"
	"github.com/uber/cadence/common/dynamicconfig/dynamicproperties"
	"github.com/uber/cadence/common/metrics"
	"github.com/uber/cadence/common/persistence"
	"github.com/uber/cadence/common/quotas"
	"github.com/uber/cadence/common/types"
)

// ratelimitedDomainManager implements persistence.DomainManager interface instrumented with rate limiter.
type ratelimitedDomainManager struct {
	wrapped       persistence.DomainManager
	rateLimiter   quotas.Limiter
	metricsClient metrics.Client
	datastoreName string
	dc            *dynamicconfig.Collection
}

// NewDomainManager creates a new instance of DomainManager with ratelimiter.
func NewDomainManager(
	wrapped persistence.DomainManager,
	rateLimiter quotas.Limiter,
	metricsClient metrics.Client,
	datastoreName string,
	dc *dynamicconfig.Collection,
) persistence.DomainManager {
	return &ratelimitedDomainManager{
		wrapped:       wrapped,
		rateLimiter:   rateLimiter,
		metricsClient: metricsClient,
		datastoreName: datastoreName,
		dc:            dc,
	}
}

func (c *ratelimitedDomainManager) Close() {
	c.wrapped.Close()
	return
}

func (c *ratelimitedDomainManager) CreateDomain(ctx context.Context, request *persistence.CreateDomainRequest) (cp1 *persistence.CreateDomainResponse, err error) {
	if c.metricsClient != nil {
		scope := c.metricsClient.Scope(metrics.PersistenceCreateShardScope, metrics.DatastoreTag(c.datastoreName))
		scope.UpdateGauge(metrics.PersistenceQuota, float64(c.rateLimiter.Limit()))
	}

	if ok := c.rateLimiter.Allow(); !ok {
		callerInfo := types.GetCallerInfoFromContext(ctx)
		if c.shouldBypassRateLimit(callerInfo.GetCallerType()) {
			return c.wrapped.CreateDomain(ctx, request)
		}
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.CreateDomain(ctx, request)
}

func (c *ratelimitedDomainManager) DeleteDomain(ctx context.Context, request *persistence.DeleteDomainRequest) (err error) {
	if c.metricsClient != nil {
		scope := c.metricsClient.Scope(metrics.PersistenceCreateShardScope, metrics.DatastoreTag(c.datastoreName))
		scope.UpdateGauge(metrics.PersistenceQuota, float64(c.rateLimiter.Limit()))
	}

	if ok := c.rateLimiter.Allow(); !ok {
		callerInfo := types.GetCallerInfoFromContext(ctx)
		if c.shouldBypassRateLimit(callerInfo.GetCallerType()) {
			return c.wrapped.DeleteDomain(ctx, request)
		}
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.DeleteDomain(ctx, request)
}

func (c *ratelimitedDomainManager) DeleteDomainByName(ctx context.Context, request *persistence.DeleteDomainByNameRequest) (err error) {
	if c.metricsClient != nil {
		scope := c.metricsClient.Scope(metrics.PersistenceCreateShardScope, metrics.DatastoreTag(c.datastoreName))
		scope.UpdateGauge(metrics.PersistenceQuota, float64(c.rateLimiter.Limit()))
	}

	if ok := c.rateLimiter.Allow(); !ok {
		callerInfo := types.GetCallerInfoFromContext(ctx)
		if c.shouldBypassRateLimit(callerInfo.GetCallerType()) {
			return c.wrapped.DeleteDomainByName(ctx, request)
		}
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.DeleteDomainByName(ctx, request)
}

func (c *ratelimitedDomainManager) GetDomain(ctx context.Context, request *persistence.GetDomainRequest) (gp1 *persistence.GetDomainResponse, err error) {
	if c.metricsClient != nil {
		scope := c.metricsClient.Scope(metrics.PersistenceCreateShardScope, metrics.DatastoreTag(c.datastoreName))
		scope.UpdateGauge(metrics.PersistenceQuota, float64(c.rateLimiter.Limit()))
	}

	if ok := c.rateLimiter.Allow(); !ok {
		callerInfo := types.GetCallerInfoFromContext(ctx)
		if c.shouldBypassRateLimit(callerInfo.GetCallerType()) {
			return c.wrapped.GetDomain(ctx, request)
		}
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.GetDomain(ctx, request)
}

func (c *ratelimitedDomainManager) GetMetadata(ctx context.Context) (gp1 *persistence.GetMetadataResponse, err error) {
	if c.metricsClient != nil {
		scope := c.metricsClient.Scope(metrics.PersistenceCreateShardScope, metrics.DatastoreTag(c.datastoreName))
		scope.UpdateGauge(metrics.PersistenceQuota, float64(c.rateLimiter.Limit()))
	}

	if ok := c.rateLimiter.Allow(); !ok {
		callerInfo := types.GetCallerInfoFromContext(ctx)
		if c.shouldBypassRateLimit(callerInfo.GetCallerType()) {
			return c.wrapped.GetMetadata(ctx)
		}
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.GetMetadata(ctx)
}

func (c *ratelimitedDomainManager) GetName() (s1 string) {
	return c.wrapped.GetName()
}

func (c *ratelimitedDomainManager) ListDomains(ctx context.Context, request *persistence.ListDomainsRequest) (lp1 *persistence.ListDomainsResponse, err error) {
	if c.metricsClient != nil {
		scope := c.metricsClient.Scope(metrics.PersistenceCreateShardScope, metrics.DatastoreTag(c.datastoreName))
		scope.UpdateGauge(metrics.PersistenceQuota, float64(c.rateLimiter.Limit()))
	}

	if ok := c.rateLimiter.Allow(); !ok {
		callerInfo := types.GetCallerInfoFromContext(ctx)
		if c.shouldBypassRateLimit(callerInfo.GetCallerType()) {
			return c.wrapped.ListDomains(ctx, request)
		}
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.ListDomains(ctx, request)
}

func (c *ratelimitedDomainManager) UpdateDomain(ctx context.Context, request *persistence.UpdateDomainRequest) (err error) {
	if c.metricsClient != nil {
		scope := c.metricsClient.Scope(metrics.PersistenceCreateShardScope, metrics.DatastoreTag(c.datastoreName))
		scope.UpdateGauge(metrics.PersistenceQuota, float64(c.rateLimiter.Limit()))
	}

	if ok := c.rateLimiter.Allow(); !ok {
		callerInfo := types.GetCallerInfoFromContext(ctx)
		if c.shouldBypassRateLimit(callerInfo.GetCallerType()) {
			return c.wrapped.UpdateDomain(ctx, request)
		}
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.UpdateDomain(ctx, request)
}

func (c *ratelimitedDomainManager) shouldBypassRateLimit(callerType types.CallerType) bool {
	if c.dc == nil {
		return false
	}

	bypassCallerTypes := c.dc.GetListProperty(dynamicproperties.PersistenceRateLimiterBypassCallerTypes)()
	for _, bypassType := range bypassCallerTypes {
		if bypassTypeStr, ok := bypassType.(string); ok {
			if types.ParseCallerType(bypassTypeStr) == callerType {
				return true
			}
		}
	}
	return false
}
