package ratelimited

// Code generated by gowrap. DO NOT EDIT.
// template: ../templates/ratelimited.tmpl
// gowrap: http://github.com/hexdigest/gowrap

import (
	"context"

	"github.com/uber/cadence/common/metrics"
	"github.com/uber/cadence/common/persistence"
	"github.com/uber/cadence/common/quotas"
)

// ratelimitedQueueManager implements persistence.QueueManager interface instrumented with rate limiter.
type ratelimitedQueueManager struct {
	wrapped       persistence.QueueManager
	rateLimiter   quotas.Limiter
	metricsClient metrics.Client
	datastoreName string
}

// NewQueueManager creates a new instance of QueueManager with ratelimiter.
func NewQueueManager(
	wrapped persistence.QueueManager,
	rateLimiter quotas.Limiter,
	metricsClient metrics.Client,
	datastoreName string,
) persistence.QueueManager {
	return &ratelimitedQueueManager{
		wrapped:       wrapped,
		rateLimiter:   rateLimiter,
		metricsClient: metricsClient,
		datastoreName: datastoreName,
	}
}

func (c *ratelimitedQueueManager) Close() {
	c.wrapped.Close()
	return
}

func (c *ratelimitedQueueManager) DeleteMessageFromDLQ(ctx context.Context, request *persistence.DeleteMessageFromDLQRequest) (err error) {
	if c.metricsClient != nil {
		scope := c.metricsClient.Scope(metrics.PersistenceCreateShardScope, metrics.DatastoreTag(c.datastoreName))
		scope.UpdateGauge(metrics.PersistenceQuota, float64(c.rateLimiter.Limit()))
	}
	if ok := c.rateLimiter.Allow(); !ok {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.DeleteMessageFromDLQ(ctx, request)
}

func (c *ratelimitedQueueManager) DeleteMessagesBefore(ctx context.Context, request *persistence.DeleteMessagesBeforeRequest) (err error) {
	if c.metricsClient != nil {
		scope := c.metricsClient.Scope(metrics.PersistenceCreateShardScope, metrics.DatastoreTag(c.datastoreName))
		scope.UpdateGauge(metrics.PersistenceQuota, float64(c.rateLimiter.Limit()))
	}
	if ok := c.rateLimiter.Allow(); !ok {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.DeleteMessagesBefore(ctx, request)
}

func (c *ratelimitedQueueManager) EnqueueMessage(ctx context.Context, request *persistence.EnqueueMessageRequest) (err error) {
	if c.metricsClient != nil {
		scope := c.metricsClient.Scope(metrics.PersistenceCreateShardScope, metrics.DatastoreTag(c.datastoreName))
		scope.UpdateGauge(metrics.PersistenceQuota, float64(c.rateLimiter.Limit()))
	}
	if ok := c.rateLimiter.Allow(); !ok {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.EnqueueMessage(ctx, request)
}

func (c *ratelimitedQueueManager) EnqueueMessageToDLQ(ctx context.Context, request *persistence.EnqueueMessageToDLQRequest) (err error) {
	if c.metricsClient != nil {
		scope := c.metricsClient.Scope(metrics.PersistenceCreateShardScope, metrics.DatastoreTag(c.datastoreName))
		scope.UpdateGauge(metrics.PersistenceQuota, float64(c.rateLimiter.Limit()))
	}
	if ok := c.rateLimiter.Allow(); !ok {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.EnqueueMessageToDLQ(ctx, request)
}

func (c *ratelimitedQueueManager) GetAckLevels(ctx context.Context, request *persistence.GetAckLevelsRequest) (gp1 *persistence.GetAckLevelsResponse, err error) {
	if c.metricsClient != nil {
		scope := c.metricsClient.Scope(metrics.PersistenceCreateShardScope, metrics.DatastoreTag(c.datastoreName))
		scope.UpdateGauge(metrics.PersistenceQuota, float64(c.rateLimiter.Limit()))
	}
	if ok := c.rateLimiter.Allow(); !ok {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.GetAckLevels(ctx, request)
}

func (c *ratelimitedQueueManager) GetDLQAckLevels(ctx context.Context, request *persistence.GetDLQAckLevelsRequest) (gp1 *persistence.GetDLQAckLevelsResponse, err error) {
	if c.metricsClient != nil {
		scope := c.metricsClient.Scope(metrics.PersistenceCreateShardScope, metrics.DatastoreTag(c.datastoreName))
		scope.UpdateGauge(metrics.PersistenceQuota, float64(c.rateLimiter.Limit()))
	}
	if ok := c.rateLimiter.Allow(); !ok {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.GetDLQAckLevels(ctx, request)
}

func (c *ratelimitedQueueManager) GetDLQSize(ctx context.Context, request *persistence.GetDLQSizeRequest) (gp1 *persistence.GetDLQSizeResponse, err error) {
	if c.metricsClient != nil {
		scope := c.metricsClient.Scope(metrics.PersistenceCreateShardScope, metrics.DatastoreTag(c.datastoreName))
		scope.UpdateGauge(metrics.PersistenceQuota, float64(c.rateLimiter.Limit()))
	}
	if ok := c.rateLimiter.Allow(); !ok {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.GetDLQSize(ctx, request)
}

func (c *ratelimitedQueueManager) RangeDeleteMessagesFromDLQ(ctx context.Context, request *persistence.RangeDeleteMessagesFromDLQRequest) (err error) {
	if c.metricsClient != nil {
		scope := c.metricsClient.Scope(metrics.PersistenceCreateShardScope, metrics.DatastoreTag(c.datastoreName))
		scope.UpdateGauge(metrics.PersistenceQuota, float64(c.rateLimiter.Limit()))
	}
	if ok := c.rateLimiter.Allow(); !ok {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.RangeDeleteMessagesFromDLQ(ctx, request)
}

func (c *ratelimitedQueueManager) ReadMessages(ctx context.Context, request *persistence.ReadMessagesRequest) (rp1 *persistence.ReadMessagesResponse, err error) {
	if c.metricsClient != nil {
		scope := c.metricsClient.Scope(metrics.PersistenceCreateShardScope, metrics.DatastoreTag(c.datastoreName))
		scope.UpdateGauge(metrics.PersistenceQuota, float64(c.rateLimiter.Limit()))
	}
	if ok := c.rateLimiter.Allow(); !ok {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.ReadMessages(ctx, request)
}

func (c *ratelimitedQueueManager) ReadMessagesFromDLQ(ctx context.Context, request *persistence.ReadMessagesFromDLQRequest) (rp1 *persistence.ReadMessagesFromDLQResponse, err error) {
	if c.metricsClient != nil {
		scope := c.metricsClient.Scope(metrics.PersistenceCreateShardScope, metrics.DatastoreTag(c.datastoreName))
		scope.UpdateGauge(metrics.PersistenceQuota, float64(c.rateLimiter.Limit()))
	}
	if ok := c.rateLimiter.Allow(); !ok {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.ReadMessagesFromDLQ(ctx, request)
}

func (c *ratelimitedQueueManager) UpdateAckLevel(ctx context.Context, request *persistence.UpdateAckLevelRequest) (err error) {
	if c.metricsClient != nil {
		scope := c.metricsClient.Scope(metrics.PersistenceCreateShardScope, metrics.DatastoreTag(c.datastoreName))
		scope.UpdateGauge(metrics.PersistenceQuota, float64(c.rateLimiter.Limit()))
	}
	if ok := c.rateLimiter.Allow(); !ok {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.UpdateAckLevel(ctx, request)
}

func (c *ratelimitedQueueManager) UpdateDLQAckLevel(ctx context.Context, request *persistence.UpdateDLQAckLevelRequest) (err error) {
	if c.metricsClient != nil {
		scope := c.metricsClient.Scope(metrics.PersistenceCreateShardScope, metrics.DatastoreTag(c.datastoreName))
		scope.UpdateGauge(metrics.PersistenceQuota, float64(c.rateLimiter.Limit()))
	}
	if ok := c.rateLimiter.Allow(); !ok {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.UpdateDLQAckLevel(ctx, request)
}
