package ratelimited

// Code generated by gowrap. DO NOT EDIT.
// template: ../templates/ratelimited.tmpl
// gowrap: http://github.com/hexdigest/gowrap

import (
	"context"

	"github.com/uber/cadence/common/dynamicconfig"
	"github.com/uber/cadence/common/dynamicconfig/dynamicproperties"
	"github.com/uber/cadence/common/metrics"
	"github.com/uber/cadence/common/persistence"
	"github.com/uber/cadence/common/quotas"
	"github.com/uber/cadence/common/types"
)

// ratelimitedShardManager implements persistence.ShardManager interface instrumented with rate limiter.
type ratelimitedShardManager struct {
	wrapped       persistence.ShardManager
	rateLimiter   quotas.Limiter
	metricsClient metrics.Client
	datastoreName string
	dc            *dynamicconfig.Collection
}

// NewShardManager creates a new instance of ShardManager with ratelimiter.
func NewShardManager(
	wrapped persistence.ShardManager,
	rateLimiter quotas.Limiter,
	metricsClient metrics.Client,
	datastoreName string,
	dc *dynamicconfig.Collection,
) persistence.ShardManager {
	return &ratelimitedShardManager{
		wrapped:       wrapped,
		rateLimiter:   rateLimiter,
		metricsClient: metricsClient,
		datastoreName: datastoreName,
		dc:            dc,
	}
}

func (c *ratelimitedShardManager) Close() {
	c.wrapped.Close()
	return
}

func (c *ratelimitedShardManager) CreateShard(ctx context.Context, request *persistence.CreateShardRequest) (err error) {
	if c.metricsClient != nil {
		scope := c.metricsClient.Scope(metrics.PersistenceCreateShardScope, metrics.DatastoreTag(c.datastoreName))
		scope.UpdateGauge(metrics.PersistenceQuota, float64(c.rateLimiter.Limit()))
	}

	if ok := c.rateLimiter.Allow(); !ok {
		callerInfo := types.GetCallerInfoFromContext(ctx)
		if c.shouldBypassRateLimit(callerInfo.GetCallerType()) {
			return c.wrapped.CreateShard(ctx, request)
		}
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.CreateShard(ctx, request)
}

func (c *ratelimitedShardManager) GetName() (s1 string) {
	return c.wrapped.GetName()
}

func (c *ratelimitedShardManager) GetShard(ctx context.Context, request *persistence.GetShardRequest) (gp1 *persistence.GetShardResponse, err error) {
	if c.metricsClient != nil {
		scope := c.metricsClient.Scope(metrics.PersistenceCreateShardScope, metrics.DatastoreTag(c.datastoreName))
		scope.UpdateGauge(metrics.PersistenceQuota, float64(c.rateLimiter.Limit()))
	}

	if ok := c.rateLimiter.Allow(); !ok {
		callerInfo := types.GetCallerInfoFromContext(ctx)
		if c.shouldBypassRateLimit(callerInfo.GetCallerType()) {
			return c.wrapped.GetShard(ctx, request)
		}
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.GetShard(ctx, request)
}

func (c *ratelimitedShardManager) UpdateShard(ctx context.Context, request *persistence.UpdateShardRequest) (err error) {
	if c.metricsClient != nil {
		scope := c.metricsClient.Scope(metrics.PersistenceCreateShardScope, metrics.DatastoreTag(c.datastoreName))
		scope.UpdateGauge(metrics.PersistenceQuota, float64(c.rateLimiter.Limit()))
	}

	if ok := c.rateLimiter.Allow(); !ok {
		callerInfo := types.GetCallerInfoFromContext(ctx)
		if c.shouldBypassRateLimit(callerInfo.GetCallerType()) {
			return c.wrapped.UpdateShard(ctx, request)
		}
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.UpdateShard(ctx, request)
}

func (c *ratelimitedShardManager) shouldBypassRateLimit(callerType types.CallerType) bool {
	if c.dc == nil {
		return false
	}

	bypassCallerTypes := c.dc.GetListProperty(dynamicproperties.PersistenceRateLimiterBypassCallerTypes)()
	for _, bypassType := range bypassCallerTypes {
		if bypassTypeStr, ok := bypassType.(string); ok {
			if types.ParseCallerType(bypassTypeStr) == callerType {
				return true
			}
		}
	}
	return false
}
